### PR TITLE
support for lineage-19.0

### PR DESCRIPTION
**Pull request by bananer**
If you're curious, build yourself with docker tag `lineageos4microg/docker-lineage-cicd:lineage-19.0`

### CODE REVIEW

**Comment by Exodusnick** [comment]
[lineage-19.0-20220219-microG-signed-hero2lte.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/8104065/lineage-19.0-20220219-microG-signed-hero2lte.log)
from 98%

FAILED: out/soong/.intermediates/packages/modules/Permission/PermissionController/PermissionController/android_common_apex30/javac/PermissionController.jar

**Comment by bananer** [comment]
@Exodusnick could it be that you tried to build with signature spoofing on first and then without? That would explain the error since I forgot to reset the new patch path ( https://github.com/lineageos4microg/docker-lineage-cicd/pull/269/commits/db95c8a729bcad10752de5355ff4bd395fef0599) . If you, try pulling the newest version (`docker pull lineageos4microg/docker-lineage-cicd:lineage-19.0`) and run again.

There is also an issue with the prebuilts repo (https://github.com/lineageos4microg/android_vendor_partner_gms/issues/5), so you might need to switch to `revision="product_modules"` in your manifest xml for it.

**Comment by Exodusnick** [comment]
@bananer no have build directly with active signature spoofing .
I will try again later without (lineageos4microg/android_vendor_partner_gms#5).

**Comment by bananer** [comment]
Appreciate the effort, but only a build with signature spoofing and with microGMS can tell us if the microG self check passes or if we're still missing something.

I tried to build for `sunfish`, but that failed when builing the kernel: error 137, out of memory. Might be fixable with more swap.

Currently building for `barbet`, seems like it's doing better.

**Comment by bananer** [comment]
There was another change needed in the signature spoofing patches. I took the chance and cleaned up the code we're adding a bit.

**Comment by Exodusnick** [comment]
@bananer sorry you misunderstood me I use other prebuilts repo .
if yours work I will use them.
I will come but only on the weekend to it because I do not have much time.

**Comment by Exodusnick** [comment]
> see at 98%
> 
> [lineage-19.0-20220219-microG-signed-hero2lte.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/8104065/lineage-19.0-20220219-microG-signed-hero2lte.log)
> 
> FAILED: out/soong/.intermediates/packages/modules/Permission/PermissionController/PermissionController/android_common_apex30/javac/PermissionController.jar

could there be a problem with the build container in my case?

**Comment by poshul** [comment]
Hmm, trying to build with this docker tag I get the following:
`error: mismatch in the <uses-library> tags between the build system and the manifest:
        - required libraries in build system: []
                         vs. in the manifest: [com.android.location.provider]
        - optional libraries in build system: []
                         vs. in the manifest: []
        - tags in the manifest (prebuilts/prebuiltapks/GmsCore/com.google.android.gms-212658044.apk):
                uses-library:'com.android.location.provider'
note: the following options are available:
        - to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-compilation in dexpreopt)
        - to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
        - to fix the check, make build system properties coherent with the manifest
        - see build/make/Changes.md for details
`

**Comment by bananer** [comment]
rebased and changed to 19.1 in #284

**Pull request closed without merging**
