### PR TITLE
Sweep out QC Location in rro

### PR DESCRIPTION
**Pull request by Iey4iej3**
Patch against a commit like https://review.lineageos.org/c/LineageOS/android_device_xiaomi_beryllium/+/252267/2/device-props.mk

### CODE REVIEW

**Comment by Iey4iej3** [comment]
In fact, we can use `sed -i "1i PRODUCT_PROPERTY_OVERRIDES += persist.vendor.overlay.izat.optin=none" "vendor/$vendor/config/common.mk"`. I adopted the style of a previous usage of `sed`.

**Comment by corna** [comment]
Thanks, I will test it this weekend. Anyone willing to try the resulting builds? If so, which decice(s)?

**Comment by sepo** [comment]
I can test beryllium.

**Comment by Iey4iej3** [comment]
I am not sure whether I have time to test or TWRP backup will work properly (I have never succeeded to restore backups on my new device yet). But if you succeed to build but UnifiedNlp still does not work, it would be helpful to get the values of `config_enableNetworkLocationOverlay` and `config_enableFusedLocationOverlay` in `/system/framework/framework-res.apk` and `/vendor/overlay/framework-res__auto_generated_rro.apk` to see whether the values were overridden or not.

**Comment by corna** [comment]
@sepo 
[Here it is](https://lineage.microg.org/testimages/lineage-16.0-20191102-microG-test-noqcomizat-beryllium.zip), let me know. It is signed with our usual key so, if it works, you can keep this build installed and wait for the usual OTA update.

**Comment by sepo** [comment]
@corna thank you for the build. Sadly it doesn't fix the problem. I did a clean install.

**Comment by sepo** [comment]
Ok "System supports location provider" is not checked, but it seems that I get the location nevertheless. At least osmand shows my position with the Mozilla location provider enabled.

**Comment by sepo** [comment]
After a reboot it does not work anymore in osmand. May it worked before the reboot because I had GPS activated just before the test.
I will extract the values of config_enableNetworkLocationOverlay and config_enableFusedLocationOverlay tomorrow.

**Comment by Iey4iej3** [comment]
@sepo My guess is that this patch does not override these values effectively. By the way, in fact, you can get locations even when UnifiedNlp is not registered in the system - I don't know why. However, you need some efforts: first, Mozilla NlpBackend is a bit buggy. [Local GSM Nlp Backend](https://f-droid.org/en/packages/org.fitchfamily.android.gsmlocation/) is better (but you need to download location data before your first use). Second, you need to disable and re-enable the Nlp Backend after (maybe you need to try this several times), and then you would get location (it works in my case). I don't know why. For a reference, see https://github.com/lineageos4microg/android_prebuilts_prebuiltapks/issues/22#issuecomment-544442041

**Comment by Iey4iej3** [comment]
@sepo Not necessary to extract these files. I downloaded the built image and I understood how to extract directly the files instead of flashing. I see that `izat.optin=rro` still appears in `/vendor/build.prop`. We need to understand more about the building process to know what to do.

@corna Could you please manually modify `device-props.mk` removing
> PRODUCT_PROPERTY_OVERRIDES += \\
> persist.vendor.overlay.izat.optin=rro

and build the LOS for microG to test by, say, @sepo, to determine whether this is the *only* configuration that disables UnifiedNlp? Thanks!

**Comment by Iey4iej3** [comment]
My understanding might be completely incorrect. I extracted the official LOS image, and in `/system/framework/framework-res.apk`, the values of `config_enableNetworkLocationOverlay` and `config_enableFusedLocationOverlay` are also `true`.

Previously I saw these `true` are proofs that microG overlay was inserted. It might not be so - since the overlays are now inserted into `/vendor` rather than `/system`. Consequently, maybe modifying `device-props.mk` here does not work no matter how.

**Pull request closed without merging**
