### PR TITLE
More precise titling of the build name.

### PR DESCRIPTION
**Pull request by john-soda**
Adds microG to the buildname and looks if the build will be signed or not. If yes, adds it also to name.

### CODE REVIEW

**Comment by john-soda** [comment]
Ensures that there is no confusion if you share your build on XDA with others. Because that's the Problem with the current naming.

**Comment by cssr45** [comment]
You can add this line to the build script and it will build with that as the ROM/.zip file name.

 -e "RELEASE_TYPE=UNOFFICIAL-microG-john-soda-signed" \

**Comment by corna** [comment]
Note that, while we publish this under lineageos4microg (and we use this to build LineageOS for microG), this docker image is not strictly linked to microG, as it can also be used to build images without microG (as outlined in the README).

Moreover, if you want to add multiple "tags" to the image release name, you can specify them in the RELEASE_TYPE variable, as explained by @cssr45

**Comment by john-soda** [comment]
Good to know that there is a Release_Type variable! Thanks! But the information, if the build is signed or not, is a vital information! So I would prefer to keep automated switch for signed or not signed in the build name.

**Pull request closed without merging**
