### PR TITLE
Copy images from IMAGES directory (fixes #405)

### LINKED ISSUE #405: Problems flashing devices which have their recovery in vendor_boot partition
Hi,

I've recently tried to install lineageos w/microg on bluejay (pixel 6a).  
I have used the files from https://download.lineage.microg.org/bluejay/.

There are a few things which are not working right now:
1. The [installation guide](https://wiki.lineageos.org/devices/bluejay/install#booting-a-custom-recovery-using-fastboot) mentions flashing the `vendor_boot` partition with a `vendor_boot.img` file.  
This file does not exist on the [download page](https://download.lineage.microg.org/bluejay/) for the build from the 6th of march.  
I thought this should've been added with [this](https://github.com/lineageos4microg/docker-lineage-cicd/commit/ba58e6bd8f36222c8f8ad975c4abad9bafbf236d) 3rd of february commit from @bananer, but apparantly something is not working here.

2. I have extracted `payload.bin` from the zip, and extracted that using `payload_dumper`. Then I flashed `vendor_boot.img` which I got from there.
Unfortunately, booting into recovery did not work. Instead, the device fails to boot.

### PR DESCRIPTION
**Pull request by Yannik**
Draft PR, testing right now whether this works as expected.

### CODE REVIEW

**Comment by Yannik** [comment]
Can confirm this works as desired:

```
>> [Fri Aug  4 11:39:32 UTC 2023] Copying boot.img to /srv/zips/bluejay/lineage-20.0-20230804-UNOFFICIAL-bluejay-boot.img
>> [Fri Aug  4 11:39:32 UTC 2023] Copying vendor_boot.img to /srv/zips/bluejay/lineage-20.0-20230804-UNOFFICIAL-bluejay-vendor_boot.img
>> [Fri Aug  4 11:39:32 UTC 2023] Copying dtbo.img to /srv/zips/bluejay/lineage-20.0-20230804-UNOFFICIAL-bluejay-dtbo.img
>> [Fri Aug  4 11:39:32 UTC 2023] Copying super_empty.img to /srv/zips/bluejay/lineage-20.0-20230804-UNOFFICIAL-bluejay-super_empty.img
>> [Fri Aug  4 11:39:32 UTC 2023] Copying vbmeta.img to /srv/zips/bluejay/lineage-20.0-20230804-UNOFFICIAL-bluejay-vbmeta.img
>> [Fri Aug  4 11:39:32 UTC 2023] Finishing build for bluejay
```



```
$ ls -alsh zips/bluejay/
insgesamt 1,2G
4,0K drwxr-xr-x 2 root root 4,0K Aug  4 13:39 .
4,0K drwxr-xr-x 3 root root 4,0K Aug  3 14:50 ..
 65M -rw-r--r-- 1 root root  64M Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay-boot.img
4,0K -rw-r--r-- 1 root root  116 Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay-boot.img.sha256sum
1,1M -rw-r--r-- 1 root root  16M Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay-dtbo.img
4,0K -rw-r--r-- 1 root root  116 Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay-dtbo.img.sha256sum
8,0K -rw-r--r-- 1 root root 5,0K Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay-super_empty.img
4,0K -rw-r--r-- 1 root root  123 Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay-super_empty.img.sha256sum
8,0K -rw-r--r-- 1 root root 8,0K Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay-vbmeta.img
4,0K -rw-r--r-- 1 root root  118 Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay-vbmeta.img.sha256sum
 64M -rw-r--r-- 1 root root  64M Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay-vendor_boot.img
4,0K -rw-r--r-- 1 root root  123 Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay-vendor_boot.img.sha256sum
1,1G -rw-r--r-- 1 root root 1,1G Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay.zip
8,0K -rw-r--r-- 1 root root 5,2K Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay.zip.prop
4,0K -rw-r--r-- 1 root root  111 Aug  4 13:39 lineage-20.0-20230804-UNOFFICIAL-bluejay.zip.sha256sum
```

**Comment by Lanchon** [comment]
(squash if you can for least friction)

**Comment by Yannik** [comment]
> (squash if you can for least friction; you can force push)

Done, even though there is a very easy to use squash feature integrated into github :-)

**Comment by petefoth** [comment]
Added 'Not a bug` and 'Wont merge' labels

See https://github.com/lineageos4microg/docker-lineage-cicd/issues/358#issuecomment-1666405638

**Comment by petefoth** [comment]
From one of the commits

> For many devices, some of these file are already in the out
> directory.
> 
> This change copies the files from
> obj/PACKAGING/target_files_intermediates/lineage_$codename-target_files-eng.root/
> instead of the versions in the out directory. Are we happy that we
> should always use these versions rather than the versions in in the
> out directory?

Answered above
> 
> Please can you describe what testing you have done on this change? (I
> don't plan to merge any changes into the master branch without
> adequate testing, and I don't have the time to run any tests myself)
> 
> Thanks

**Comment by Yannik** [comment]
@petefoth the imgs in out and IMAGES are byte-identical, so it does not make a difference.

**Comment by petefoth** [comment]
OK. So the Installation instructions for `bluejay` require the following images 
- `boot.img` and `dtbo.img` when [flashing additional patritions](https://wiki.lineageos.org/devices/bluejay/install#flashing-additional-partitions)
- `vendor_boot.img` when [booting a recvery](https://wiki.lineageos.org/devices/bluejay/install#booting-a-custom-recovery-using-fastboot)

`vbmeta.img` and `super_empty.img` are not mentioned, and are presumably not required. Or are they required for some other use case apart from the ones mentioned? If that's the case I willl need to revert [my earlier commit](https://github.com/lineageos4microg/docker-lineage-cicd/commit/ba64ea53b02642627df4bae935318dd8da20f54a) - no point clutterig ur download directories with `.img` files that are not needed

**Comment by Yannik** [comment]
@petefoth they are all required. There are devices which need them:

vbmeta:
https://wiki.lineageos.org/devices/lemonades/install 

super_empty
https://wiki.lineageos.org/devices/G/install

vendor_kernel_boot:
https://wiki.lineageos.org/devices/cheetah/install

**Comment by petefoth** [comment]
@Yannik OK - thanks again

I will merge this (after the current build run completes, and any build failures have been corrected

***But*** I still believe that, given the list of needed .img files varies for different devices, then the ***correct*** place to fix this issue is in the upstream device-specific makefiles. Clearly upstream are not going to fix their makefiles, so I guess this project will have to carry their technical debt by extracting and publishing a bunch of `img` files:
1. even if they are not needed in the install process for  all devices, (e.g. `vbmeta` and `super_empty` for `bluejay)
2. where the LineageOS-published versions could be used. (Or is it the case, as @Lanchon suggests [here](https://github.com/lineageos4microg/docker-lineage-cicd/issues/405#issuecomment-1666483599) that using the LOS files would not work, perhaps because of signing issues?)

Anyway, I will merge, but under protest ;)

**Comment by Yannik** [comment]
@petefoth 
> even if they are not needed in the install process for all devices, (e.g. vbmeta and super_empty for `bluejay)

I agree this is sub-optimal, but this is a upstream issue (LineageOS also publishes these images that are not required).

Regarding merging: I have fixed the CI shellcheck issue and added `vendor_kernel_boot`.

**Comment by dicer** [comment]
Just as another data point: I made my monthly build with the current state of this PR and it worked just fine. The boot.img in the zips folder and an extracted boot.img from the main zip have the same md5sum (also vbmeta and dtbo). So looks good to me.

**Comment by petefoth** [comment]
Merging this until we have a better solution (possibly using `mka dist` to produce a flashable `-img.zip` file containing the required  `.img` files

**Pull request merged**
