### PR TITLE
 Lineageos 19.0 microg Permission Manager Does not work

### PR DESCRIPTION
**Pull request by Exodusnick**
Lineageos 19.0 microg Permission Manager Does not work
again the same problem as under lineageos 18.1 see here
https://github.com/lineageos4microg/docker-lineage-cicd/issues/176

Screenshot_20220317-100515_Berechtigungssteuerung

docker run \
    -e "CCACHE_SIZE=100G" \
    -e "BRANCH_NAME=lineage-19.0" \
    -e "DEVICE_LIST=herolte,hero2lte" \
    -e "RELEASE_TYPE=microG-signed" \
    -e "SIGN_BUILDS=true" \
    -e "SIGNATURE_SPOOFING=no" \
    -e "INCLUDE_PROPRIETARY=false" \

### CODE REVIEW

**Comment by Exodusnick** [comment]
@bananer 
if you need more info i will be happy to help you again

**Comment by Exodusnick** [comment]
see here

**Comment by Exodusnick** [comment]
see here 

Screenshot_20220317-104210_microG Services Core

Screenshot_20220317-104258_Signature Spoofing Checker

**Comment by bananer** [comment]
>  -e "SIGNATURE_SPOOFING=no" 

I'm confused... With this, no changes to the permission system should happen, and microG should not report sig spoofing as working.

Could you post your exact docker command and the output it produces?

**Comment by Exodusnick** [comment]
I use this custom docker-lineage-cicd https://github.com/danielk43/docker-lineage-cicd : lineage-19.0-8890 
It could be possible that there is a bug there.

My docker.sh
docker run \
-e "CCACHE_SIZE=100G" \
-e "BRANCH_NAME=lineage-19.0" \
-e "DEVICE_LIST=herolte,hero2lte" \
-e "RELEASE_TYPE=microG-214816048" \
-e "SIGN_BUILDS=true" \
-e "SIGNATURE_SPOOFING=no" \
-e "INCLUDE_PROPRIETARY=false" \
-e"REPO_INIT=https://github.com/danielk43/android" \
-e "HEROLTE=true" \
-v ...= My directory
danielk43/docker-lineage-cicd:lineage-19.0-8890

**Comment by Exodusnick** [comment]
via adb logcat 
https://www.toptal.com/developers/hastebin/ubutukupuf.yaml

mtp://SAMSUNG_SAMSUNG_Android_ad0617021667195be0/Internal%20shared%20storage/Movies/screen-20220317-163401.mp4

**Pull request closed without merging**
