### PR TITLE
Restructure build script for 21.0 builds 

### LINKED ISSUE #667: 'Upgrade' link on the web site is out-of-date
The 'Upgrade' section of the website includes a link to a LineageOS  Wiki page (https://wiki.lineageos.org/upgrade_guides.html) that no longer exists.

Upgrade instructions in the LOS documentation are now in device-specific pages. Our web site needs to be updated

Reported in [this forum post](https://xdaforums.com/t/lineageos-for-microg.3700997/post-89663341)

### LINKED ISSUE #677: September 21.0 builds failing
Looks like all the builds are failing this month's run

### PR DESCRIPTION
**Pull request by petefoth**
This PR is intended to fix #677 

This branch is ready to merge to master.
- used to make 21.0 and 20.0 builds without problems
- not tried building 19.1 since here are currently no 19.1 devices

The old `master` branch (retaining the old build structure, so will only work for 21.0 builds if vendor blobs are supplied by a manifest rather than using `INCLUDE_PROPRIETARY=true`) has been named to `legacy`. (Strictly speaking, a new branch called `legacy` was created from the `master` branch before these changes in this PR was merged

-----------------
~~Tested by trying a build for `akari` (on a very slow machine). The build is not yet complete, but it has got passed the point in the build where builds have been failing~~

~~If anyone else wants to try it, the image is available from Docker Hub~~

~~`docker pull lineageos4microg/docker-lineage-cicd:pf-restructure-build`~~

### CODE REVIEW

**Comment by petefoth** [comment]
Using `BUILD_OVERLAY=true` fails the second device with a load of `already defined` errors: stuff in `tmp/merged` also exists in normal `$SRCDIR`
```
PRODUCT_SOONG_NAMESPACES=device/sony/tama-common hardware/google/interfaces hardware/google/pixel hardware/lineage/interfaces/power-libperfmgr hardware/qcom-caf/common/libqti-perfd-client hardware/qcom-caf/sdm845 vendor/qcom/opensource/commonsys/display vendor/qcom/opensource/commonsys-intf/display vendor/qcom/opensource/display vendor/qcom/opensource/data-ipa-cfg-mgr-legacy-um vendor/qcom/opensource/dataservices hardware/qcom-caf/wlan
============================================
error: merged/external/go-cmp/Android.gen.bp:4:1: module "go-cmp" already defined
       external/go-cmp/Android.gen.bp:4:1 <-- previous definition here
```
```

**Comment by petefoth** [comment]
That error message indicates that you have applied the signature spoofing patches, which indicates either that you are not using the image built from the `pf-restructure-build` branch which does not apply the signature spoofing patches, or that you are using that branch on a 'dirty` source tree which already has the signature spoofing patches applied.

Some points to bear in mind
1. This branch, and the docker image built from it, **_is a work-in-progress_** (hence the 'DRAFT:' tag in the PR title) and **_is not ready to be used_**. It is subject to change as I test and debug the changes made so far. The error message you quote shows you ran  the image at around 08:20 on 5th September,since which time there have been several more commits to the branch. I have edited the PR description to try and make that a bit clearer. It will not be ready for use until it has been adequately tested, and any errors or missing functionality are ether corrected and / or documented in issues or the documentation. 
2. The branch **_does not_** apply the signature spoofing patches, as they are not needed for 21.0 `userdebug` builds, since the upstream code [now allows restricted signature spoofing for 18.1, 20.1 and 21.0 debuggable builds](https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/383740) (e.g. our official `userdebug` builds, which are our current priority).
3. The patches **_will_** be needed to make functioning non-debuggable builds (i.e. `user` builds, but that is not going to happen in this branch, at least until the fix for our official builds has been properly tested, which is our current priority.
4. If you need to make `user` builds then 
    1. you will need to apply the patches manually: 
        1. the code to apply the patches manually is in file `src/build.sh` at https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L288C4-L347C1
        2. If you do apply the patches you will also need the code from https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L475-L480 which will (maybe) fix the error in your log file.
        3. As previously stated, this branch is not yet ready for use. Feel free to use it if you wish, but we wont be able to provide further support or help with it until
        >  it has been adequately tested, and any errors or missing functionality are ether corrected and / or documented in issues or the documentation.

**Comment by tduboys** [comment]
Hello, 
just for feedback, building lineage 21.0 for akari worked without issue with your docker image
new compiled image boot, OTA check with custom url is still ok, image signature with custom key is also ok.
I'm using my own android_vendor_partner_gms repo to include additional apps, this part is also ok.

**Comment by petefoth** [comment]
> just for feedback, building lineage 21.0 for akari worked without issue with your docker image

Thanks. It looks like it's fi e for 21.0 userdebug builds - it's doing the monthly builds with no problems so far 🫰

**Comment by petefoth** [comment]
OK, this branch is ready to merge to master.
- used to make 21.0 and 20.0 builds without problems
The old `master` branch - retaining the old build structure, so will only work for 21.0 builds if vendor blobs are supplied by a manifest rather than using `INCLUDE_PROPRIETARY=true`

**Pull request merged**
