### PR TITLE
[Feature] Allow building without Docker

### PR DESCRIPTION
**Pull request by gerion0**
Docker is a nice tool to deploy software on random devices since it bundles all dependencies. However, it has the big disadvantage that it [requires root](https://docs.docker.com/engine/security/#docker-daemon-attack-surface). Docker is also the only point in the whole build process that requires root, so it effectively permits the usage on servers where one only have a user account.

This pull request allows building LineageOS without root. It aims to be minimal invasive and should not change anything of the normal usage with Docker. The mechanism is to add a special `$PREFIX` path to all (otherwise) hardcoded absolute paths. Setting `$PREFIX` to an empty string leaves the setup as is. Setting `$PREFIX` to a user writables directory supports building anywhere in the system. The Dockerfile handling is done by a simple Python script that mainly reads the environment variables and executes `init.sh`.

We tested buidling without Docker successfully on Debian Buster.

### CODE REVIEW

**Review by bananer — COMMENTED** [review]
I absolutely understand your motivation but I don't think what you're suggesting is the right approach.

Your `run.py` is mostly a minimal parser for `Dockerfile`, so any changes to the latter would have to carefully consider whether it breaks the former. This seems rather fragile to me and definitely increases the maintenance burden.

In case we want to properly support use cases without Docker, I think the following would be a better approach:

1. Create a new project containing just the scripts to download and build LineageOS, independent of Docker. Maybe start with a fork and rip out all the Docker stuff.
2. Change `docker-lineage-cicd` into a Docker wrapper around this new project

**Comment by bananer** [comment]
If your concern is mostly about Docker running as root, did you also consider these options?
- [Rootless Docker](https://docs.docker.com/engine/security/rootless/)
- [Podman](https://developers.redhat.com/blog/2020/09/25/rootless-containers-with-podman-the-basics/)

**Comment by gerion0** [comment]
Thank you for the review. Yes, `run.py` is essentially a parser for the `Dockerfile`. In this regard, the `Dockerfile` acts mainly as a config file to set the correct project configurations.

Of course this approach makes the non-Docker build to a second class citizen. It could break easily and is added subsequently. We choose it, because it is minimal invasive to the current workflow.

So I like to hear that you are open to support a non-Docker build in general. I also like your proposed approach. I think, this requires a few design decisions that it makes sense to clarify in advance.

### CLI argument handling

For a non-Docker build, there must be some mechanism to configure the project parameters. Currently, this is done by environment variables that can either be set within the Dockerfile directly or via command line. This covers the use case to modify a bunch of arguments at once (the initial configuration) and to change single arguments on a per use base.

Typically, CLI programs achieve this by CLI arguments and the possibility to read a config file. Environment variables are mostly [not taken](https://nibblestew.blogspot.com/2021/03/never-use-environment-variables-for.html) for that. For Docker, however, environment variables are the simplest configuration method and Docker starts always with a fresh environment. Therefore, I see this possiblities:

1. Implement the main CLI program in a way that is takes parameters via CLI arguments and a config file. As a second step, write a wrapper script for Docker that takes the Docker environment and converts it to a proper config file and then invokes the main program
2. Implement the main CLI program to take parameters via CLI arguments and a config file but read environment variables (optionally), if they are specified.

I would prefer 2.

### Paths
Currently, the project uses the hardcoded `root` directory to invoke other script. I would change this to paths relative to the current running script. Then it can be configured to be `/root/` for a Docker build again and anywhere else for a non-Docker build.

### Programming language
Argument handling and parsing is way easier to handle in Python than in Shell. Do you mind, if we reimplement the scripts in Python (at least `src/init.sh`)? If I see it right, most external program calls are invocations of `repo` and `git`. Most of the other stuff (`sed`,...) should be doable in Python directly.

**Comment by bananer** [comment]
Great proposal! I would support cleanly separating these concerns:

- Scripts to download, patch, build and sign LineageOS on a Linux machine where some required tools are available
- A Docker image with said requirements included, running the scripts

I agree with option 2 for argument handling.

Porting to python seems like a good idea, I don't find a lot of pleasure in shell code.

Beware that I don't officially speak for the project, I'm just a contributor.

**Comment by petefoth** [comment]
This feature request starts from the premise that

> Docker is a nice tool to deploy software on random devices since it bundles all dependencies. However, ***it has the big disadvantage that it [requires root](https://docs.docker.com/engine/security/#docker-daemon-attack-surface)***.

As has been noted above, it is ***already*** possible to run Docker without being root: see these lines from https://get.docker.com/
>   if version_gte "20.10"; then
>   echo "To run Docker as a non-privileged user, consider setting up the"
>   echo "Docker daemon in rootless mode for your user:"
>   echo
>   echo "    dockerd-rootless-setuptool.sh install"
>   echo
>   echo "Visit https://docs.docker.com/go/rootless/ to learn about rootless mode."
>   echo
>   fi

I ran `dockerd-rootless-setuptool.sh install` and I have been using Docker to build lineageos4microg without using `sudo` for some time now.

Before I did that, I used to make lineageos4microg builds outside of docker, using the 'traditional' workflow of `repo sync`, `source build/envsetup.sh`,`lunch`, `mka bacon`. To do that, I needed to  
1. set up needed environment variables - either manually or in a shell script called with `source ...`
2. create a script to apply the signature spoofing patches, and run the script after the `repo sync` but before the `source  build/envsetup.sh`

Given the above, I am not sure the proposed approach of creating a ***third*** method of building adds sufficient value to outweigh the extra effort involved in creating, testing and maintaining the code needed. Particularly when this project is so small: the maintainers have enough (too much?) to do already just keeping the build and release process rolling along and dealing with any problems that arise

I do think it is worth ***documenting*** (in our README) how to build lineageos4microg without Docker. I will happily create an issue to do that, and work on writing (and testing :) ) the documentation. But I don't want to be involved in developing, testing and maintaining code that the project won't be using (because the project makes builds on a server where builds *are* run with privileged access).

I think that the method you propose ***would*** be interesting but, as @bananer stated above, as a ***separate project***, not as part of this one. The [purpose of **this** project](https://github.com/lineageos4microg/docker-lineage-cicd#docker-lineage-cicd) is to be

> Docker microservice for LineageOS Continuous Integration and Continuous Deployment

As @bananer stated above

> In case we want to properly support use cases without Docker, I think the following would be a better approach:
> 
>     1. Create a new project containing just the scripts to download and build LineageOS, independent of Docker. Maybe start with a fork and rip out all the Docker stuff.
> 
>     2. Change `docker-lineage-cicd` into a Docker wrapper around this new project

There is nothing to stop you doing 1. And if, when it is done and working, it makes the process of making and releasing lineageos4microg builds significantly easier, then it may be worth us considering doing 2. Until then I think that our `ci/cd` process will carry on using Docker

**Comment by petefoth** [comment]
Unless anyone objects, I plan to close this PR fairly soon

**Comment by petefoth** [comment]
Closing

Added 'Won't merge' and 'Out of scope' labels

**Pull request closed without merging**
