### PR TITLE
Add support for building LineageOS-16.0

### PR DESCRIPTION
**Pull request by poshul**
I've updated the build.sh file to handle building 16.0. The current themuppets manifest does not include 16.0 and so I've also packaged a version in the src/ directory. The android P patch file is from @gudenau (https://github.com/microg/android_packages_apps_GmsCore/pull/601).

### CODE REVIEW

**Comment by poshul** [comment]
I've tested this building enchilada (Oneplus 6). Testing with another target would be appreciated.

**Comment by timokau** [comment]
CC @corna now that PIE has officially been [released](https://lineageos.org/Changelog-22/).

**Comment by corna** [comment]
Thanks
I've tried with cheeseburger but it failed due to the keys folder being outside the build path
I'll have a look

**Comment by poshul** [comment]
It looks like Soong expects the keys to be in a parent directory to the src? build/soong/paths.go contains a function `validateSafePath` which seems to be what is triggering the failure, but I can't find any documentation for why this behaviour is different between 15.1 and 16.0.

**Comment by purlupar** [comment]
what's the docker command to build pulling from poshul's fork? I'd like to test but cant get this far...

**Comment by maxammann** [comment]
@corna did you get it to work on cheeseburger?
Also if I build it myself and later install an update from the official builds I will get a key mismatch, right?

**Comment by poshul** [comment]
@purlupar:
clone my branch and run `sudo docker build .` this should return an image ID which you can use in the following command to actually build the image. 
`sudo docker run \
    -e "BRANCH_NAME=lineage-16.0" \
    -e "DEVICE_LIST=enchilada" \
    -e "SIGN_BUILDS=false" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "CUSTOM_PACKAGES=GmsCore GsfProxy FakeStore MozillaNlpBackend NominatimNlpBackend com.google.android.maps.jar FDroid FDroidPrivilegedExtension" \
    -v "/home/user/lineage:/srv/src" \
    -v "/home/user/zips:/srv/zips" \
    -v "/home/user/logs:/srv/logs" \
    -v "/home/user/cache:/srv/ccache" \
    -v "/home/user/keys:/srv/keys" \
    -v "/home/user/manifests:/srv/local_manifests" \`
and then the image ID from docker.

@maxammann Correct, you will get a key mismatch.

**Comment by corna** [comment]
It seems that a symlink to the keys folder is enough to please Soong.
Change [line 222](https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L223) to
```
      # Soong (Android 9+) complains if the signing keys are outside the build path
      ln -sf "$KEYS_DIR" user-keys
      sed -i "1s;^;PRODUCT_DEFAULT_DEV_CERTIFICATE := user-keys/releasekey\nPRODUCT_OTA_PUBLIC_KEYS := user-keys/releasekey\nPRODUCT_EXTRA_RECOVERY_KEYS := user-keys/releasekey\n\n;" "vendor/$vendor/config/common.mk"
```

Moreover some devices (like `cheeseburger`) require the `kmod` package, please include it in the `apt-get install` section in the Dockerfile.

**Comment by timokau** [comment]
I just got an "info" in the ota updater telling me about 16.0 and directing me to http://wiki.lineageos.org/upgrading.html. Might be confusing for users.

**Comment by poshul** [comment]
@corna anything else I should add? I've been running images built through this process on my Enchilada for the last week, and everything looks stable there.

**Comment by corna** [comment]
@poshul I've opened a PR on your repo, merge it and we're done

**Comment by poshul** [comment]
Merged. Thanks @corna !

**Comment by timokau** [comment]
@corna anything left to be done?

**Comment by timokau** [comment]
I just noticed that there already are LOS16 zips on download.lineage.microg.org. How is that if this isn't merged yet?

**Comment by corna** [comment]
Sorry, I forgot to merge this.

**Pull request merged**
