### PR TITLE
Lineage 20

### PR DESCRIPTION
**Pull request by bananer**
I built successfully for `taimen`. [Upstream is testing several more devices](https://review.lineageos.org/c/LineageOS/hudson/+/340461/26/lineage-build-targets). This branch should contain all necessary changes. 

Any help testing is greatly appreciated. Not recommended for your daily driver device yet. Build yourself by specifying the docker tag (`docker run ... lineageos4microg/docker-lineage-cicd:lineage-20`) or leave a comment with your device codename to request.

Report back with results, most important is the microG self-check.

### CODE REVIEW

**Comment by svalo** [comment]
Tested on a Fairphone4 (`FP4`), all self-checks are passed and no issue encountered at the moment. Please let me know if any  detail is needed

**Comment by kurt-by** [comment]
Can you build `bluejay` and share it with Mike Kuketz?
https://social.tchncs.de/@kuketzblog/109608654089358134

**Comment by jcgruenhage** [comment]
@bananer With LineageOS 20 having been released, and multiple people having reported success with this branch both on this PR and on https://github.com/lineageos4microg/docker-lineage-cicd/issues/335, is there anything left to do here? Would love to see builds on download.lineage.microg.org soon-ish.

If there is still something left to do, is that something that we could help with?

**Comment by mjenny** [comment]
At least the branch name of LOS needs to be changed from `lineage-20.0` to `lineage-20`:
https://github.com/lineageos4microg/docker-lineage-cicd/pull/366/files#diff-02f64ab7fe6df7a34979c489dccf70a9902438ab964f4fe9471534d6b7b74a76R140

**Comment by mjenny** [comment]
Hm... It's more complicated then expected since they use `lineage-20.0` for `android.git`

**Comment by bananer** [comment]
> I don't get why my docker container exists when it's supposed to init the repo.

@mjenny Check the file `repo-xxxxxxx.log` in your logs volume.

@jcgruenhage I will run a few more test builds in the next days. If no problems occur, I will enable Lineage 20 builds for the next round starting Jan 15th.

**Comment by mjenny** [comment]
@bananer 
It fails with the following:
```sh
>> [Wed Jan  4 09:35:40 UTC 2023] (Re)initializing branch repository
repo: error: "git" failed with exit status 128
  cwd: /srv/src/LINEAGE_20_0/.repo/repo.tmp
  cmd: ['git', 'config', 'remote.origin.url', 'https://gerrit.googlesource.com/git-repo']
  stderr:
  >> fatal: not in a git directory
fatal: double check your --repo-rev setting.
fatal: cloning the git-repo repository failed, will remove '.repo/repo' 
Downloading Repo source from https://gerrit.googlesource.com/git-repo
```

This is the command I used:
```sh
docker run \
    -e "BRANCH_NAME=lineage-20.0" \
    -e "DEVICE_LIST=instantnoodlep" \
    -e "SIGN_BUILDS=false" \
    -e "SIGNATURE_SPOOFING=restricted" \
    -e "WITH_GMS=false" \
    -e "BUILD_TYPE=user" \
    -e "PARALLEL_JOBS=8" \
    -e "CCACHE_SIZE=29G" \
    -v "/mnt/g/losmicrog/lineage:/srv/src" \
    -v "/mnt/g/losmicrog/zips:/srv/zips" \
    -v "/mnt/g/losmicrog/logs:/srv/logs" \
    -v "/mnt/g/losmicrog/cache:/srv/ccache" \
    -v "/mnt/g/losmicrog/keys:/srv/keys" \
    -v "/mnt/g/losmicrog/manifests:/srv/local_manifests" \
    lineageos4microg/docker-lineage-cicd:lineage-20
```

**Comment by bananer** [comment]
@mjenny never seen this kind of error. If you delete your source directory it will download everything again, which usually fixes problems with git/repo.

**Comment by mjenny** [comment]
@bananer Yeah, I don't get it. I deleted LINEAGE_20_0 folder completely but it didn't change anything.

I'm thinking about installing Linux on my machine since WSL2 implementation for accessing Windows drives is extremely slow...

**Comment by IngwiePhoenix** [comment]
I am interested in testing to build for and run on `aura` (Razer Phone 2).

Any tl;dr of how to run the build using Docker? (Win10 Pro, WSL2)

Thanks!

**Comment by Sam13** [comment]
>If no problems occur, I will enable Lineage 20 builds for the next round starting Jan 15th.

@bananer Yes, please. Waiting for the FP4 support 👍

**Comment by hydrandt** [comment]
> @jcgruenhage I will run a few more test builds in the next days. If no problems occur, I will enable Lineage 20 builds for the next round starting Jan 15th.

Did that happen, can FP4 builds be expected the next batch?

**Comment by bananer** [comment]
There was a configuration issue with docker on the build server. I fixed it now and restarted the builds, FP4 is almost halfway in the alphabetical list of devices to build for lineage-20.0, so I would expect a build for it in maybe 4-6 days.

**Comment by hydrandt** [comment]
Awesome, thanks!

**Comment by macearl** [comment]
> [...] in the alphabetical list of devices to build for lineage-20 [...] 

The first devices seem to have been build, which is great. But just out of curiosity: Is there an official list which devices are currently enqueued to receive LOS20? It seems there a quite a few devices starting with `a` and `b` which have official LOS20 releases missing if `coral` is already built. 

Or is this an indication that quite a few builds failed somewhere in the pipeline? Iirc there is no website which lists in progress/done/failed builds is that still correct?

**Comment by bananer** [comment]
Failures have been noted. For updates follow #335

**Comment by abishekmuthian** [comment]
Can I request a build for `beryllium` for testing?

**Pull request merged**
