### PR TITLE
Adds option for shallow cloning

### PR DESCRIPTION
**Pull request by svalo**
Accepts an aribitrary number of commits to allow flexibility

Fixes: #282

### CODE REVIEW

**Comment by svalo** [comment]
Hi @petefoth are there any updates on this? If there is anything that needs to be changed I can take care of it

**Comment by petefoth** [comment]
I'll make a decision this evening on which PR to merge, so the merge can happen before the September build run starts

**Comment by petefoth** [comment]
I decided to merge #431 instead, as it has more flexibility

Thanks for your contribution though.

**Comment by svalo** [comment]
> There is another PR (#431) which achieves the same but in a more general way. I was thinking merging that PR rather than this one, because it is more flexible and future-proof. I'd be interested in your comments on that PR before I make a decision

Yup, fine for me, I opened this one as I had the perception that the other was too broad and you were more favorable about the specific functionality.

Thank you!

**Pull request closed without merging**
