### PR TITLE
Add clang

### PR DESCRIPTION
**Pull request by petabyteboy**
Some devices need clang to build successfully, for example davinci (Xiaomi Mi 9T, which will soon be added to official devices)

### CODE REVIEW

**Comment by corna** [comment]
Thanks. Can you keep the apt list sorted?
Where did you find this info?

**Comment by petabyteboy** [comment]
I ran into a build error without clang, and adding it fixed this error. I also have reports of other people who can confirm this:
screenshot

I will fix the ordering right away.

**Comment by petabyteboy** [comment]
This is an example of the build failing because clang is missing.
[lineage-16.0-20191001-UNOFFICIAL-davinci.log](https://github.com/lineageos4microg/docker-lineage-cicd/files/3678129/lineage-16.0-20191001-UNOFFICIAL-davinci.log)

**Comment by spolack** [comment]
LGTM

**Pull request merged**
