### PR TITLE
Allow to configure the running user inside the docker container

### LINKED ISSUE #407: Feature request non-root user
I see that the init sh first thing copies some files having to do with /root which i assume are owned by 0:0, but it would be nice if this container could be run so that we can user docker's --user to run as a non root user. This would make it so we don't have to become root to be able to work with the files in the various volumes and we could also run subsequent OTA servers as non root using higher ports, etc. would be certainly make me feel better about security in general. :)

As is all files are created owned by 0:0 which means i can't move around or manipulate the files in the docker users' homedir either, so that's somewhat of an annoyance (though minor)

Alternatively:

could have some ENV vars USER and GROUP or just USER that accepts either a uid or uid:gid and have all possible operations that generate files in the mounted volumes run as that user AFTER root runs what it needs to. I think this is similar to how linuxserver builds their containers.

### PR DESCRIPTION
**Pull request by derMart**
implements #407

### CODE REVIEW

**Comment by petefoth** [comment]
Thanks for the PR and for spending time on this, but
1. #407 is a feature request not a bug, so there's nothing to 'fix'
2. It's a feature that the project doesn't want or need, so issue #407 is closed and this PR won't get merged
3. If the person who raised #407 wants to use your change they can pull it into their own fork

So thanks again, and I will close this PR

**Comment by derMart** [comment]
@petefoth Oh, I am a bit surprised by your reaction. Your last comment in #407:
> It is relatively straightforward to build your own docker image, based on this image, with the changes you need. If you can make the changes work for you , then the project would be happy to consider a pull request to make them available in this image.

suggested to me you would be happy about this PR. May I ask what changed your mind? Why does the project from your point of view does not want or need this feature? I implemented this PR not only because of the OP of #407. I certainly also need this functionality. It is otherwise a pain to develop and port for lineagos / microg in linux. One would need to change permissions of the mounted volume files and folders all the time if this functionality is missing. So I am very interested why you don't think this is needed and do not want it anymore. Maybe the whole thing is just a misunderstanding?

About the wording 'fix', well sure, I can certainly change that in the merge request description. I just used it as then the PR automatically gets referenced in the issue.

best

**Comment by petefoth** [comment]
OK. Firstly my apologies for my previous response: I shouldn't respond to PRs late at night without spending enough time thinking about them.

Secondly, 

> Why does the project from your point of view does not want or need this feature?

We don't need it, because 
- we always run out builds as root
- other users can run builds ***without*** root using the `rootless` setup [referenced in the issue](https://github.com/lineageos4microg/docker-lineage-cicd/issues/407#issuecomment-1493086454). This is how I use it for my own builds when  building locally.

We (I) don't particularly want it because:
1. ***any*** change risks breaking existing functionality;
2. this change adds a level of complexity - not huge, but there nevertheless;
3. to justify the risk, the change needs to bring ***significant*** benefit. I am still not sure what benefit this feature provides.  I'm happy to accept that at least one or two users would find it useful. I'm still not sure that this is enough of a benefit to justify the risk. 
    - @ShadwDrgn is this still functionality you need? 
    - @derMart would you use this functionality if it is merged?

However, I will reopen the PR. But before I would consider merging it, I would need to know what testing of the changes has been carried out. In particular I need to know that as, well as allowing the functionality it implements, it does not break the existing functionality of
1. running docker as root
2. running docker 'rootless'

I don't have time or resources to do that testing, so I would need to know that the testing has been done and has succeeded.

**Comment by petefoth** [comment]
> any change risks breaking existing functionality;

Re-opening the PR causes some checks to be run automatically. These checks have failed - running ShellCheck failed
```
./src/root_init.sh:22:41: note: Use -n instead of ! -z. [SC2236]
./src/root_init.sh:23:15: note: Double quote to prevent globbing and word splitting. [SC2086]
./src/root_init.sh:23:25: note: Double quote to prevent globbing and word splitting. [SC2086]
./src/root_init.sh:24:27: note: Double quote to prevent globbing and word splitting. [SC2086]
./src/root_init.sh:24:50: note: Double quote to prevent globbing and word splitting. [SC2086]
./src/root_init.sh:27:10: note: Double quote to prevent globbing and word splitting. [SC2086]
./src/root_init.sh:27:18: note: Double quote to prevent globbing and word splitting. [SC2086]
./src/root_init.sh:29:26: note: Double quote to prevent globbing and word splitting. [SC2086]
```

**Comment by petefoth** [comment]
> Re-opening the PR causes some checks to be run automatically. These checks have failed - running ShellCheck failed

No updates to this PR in the last two weeks. If there's no further action, I'll close it in the next few days

**Comment by derMart** [comment]
> No updates to this PR in the last two weeks. If there's no further action, I'll close it in the next few days
I am sorry, please give me a few days. I am still interested in finishing this, it is just ... not enough time and I was trying to setup a separate box where I can let the build process run, also to do proper testing.


> OK. Firstly my apologies for my previous response: I shouldn't respond to PRs late at night without spending enough time thinking about them.

Apology accepted, respectively thanks for considering the request :-)

> We don't need it, because
> 
> * we always run out builds as root
> 
> * other users can run builds _**without**_ root using the `rootless` setup [referenced in the issue](https://github.com/lineageos4microg/docker-lineage-cicd/issues/407#issuecomment-1493086454). This is how I use it for my own builds when  building locally.

Ok, I do understand your concern. Also, with this kind of code it is time consuming to do proper testing as automated testing is difficult. I will have to take a deeper look at the rootless docker setup, in any case it seems interesting. From what I understand right now it though has drawbacks IMHO which add motivation for this PR:
- The rootless daemon seems to be a bit cumbersome to setup, increasing the hurdle to use this repo for setting up a  development environment. 
- It might not be possible to have rootless and rooted docker containers running side by side at the same time, as eight the rooted docker daemon or the user docker daemon will run at the same time. This PR adds the possibility to decide to use a non root user if the system needs to run rooted containers aside.

> * @derMart would you use this functionality if it is merged?

I would use this for development on my machine (and currently already am with my fork), without the need to setup rootless docker.

> However, I will reopen the PR. But before I would consider merging it, I would need to know what testing of the changes has been carried out. In particular I need to know that as, well as allowing the functionality it implements, it does not break the existing functionality of
> 
> 1. running docker as root
> 
> 2. running docker 'rootless'
> 
> 
> I don't have time or resources to do that testing, so I would need to know that the testing has been done and has succeeded.

I understand. Right now I did some quick tests only with the rooted docker daemon:
```
sudo rm -rf src/* ccache/* keys/* logs/* zips/*
docker build -t docker-lineage-cicd-test ./docker-lineage-cicd
docker run --rm \
    -e "UID=[...]" \
    -e "BRANCH_NAME=lineage-21.0" \
    -e "DEVICE_LIST=bacon" \
    -e "SIGN_BUILDS=true" \
    -e "WITH_GMS=true" \
    -v "./src:/srv/src" \
    -v "./keys:/srv/keys" \
    -v "./zips:/srv/zips" \
    -v "./ccache:/srv/ccache" \
    -v "./logs:/srv/logs" \
    -v "./src:/srv/src" \
    docker-lineage-cicd-test
```
with UID=0, UID=myuserid and without specifying UID, which all started to build fine. However, I did only let it build the keys and started initializing / syncing the repo. I will do the same for the rootless daemon once my other box is setup. Please give me a few days for this. I am also happy to do more thorough testing if you want me to.

best

**Comment by derMart** [comment]
Ah and I forgot: To account for the fact not to add too much complexity I simplified the approach by only letting users specify the UID, hope this also helps a bit.

**Comment by derMart** [comment]
I now did all the tests. That is I started builds without UID / UID=0 for the rootless docker setup which generated files with correct permission. Also, I let a build for the device `beyond1lt` in the rootless setup finish successfully. I improved the documentation a bit for explaining the interaction with a rootless setup and I am confident that the PR is stable and ready to merge from my side :-) @petefoth Please let me know if there is anything else I should test.

**Comment by petefoth** [comment]
Thanks for taking the time to improve the change, and to do the testing

In an earlier comment I wrote
> We don't need it, because
>     * we always run out builds as root
>     * other users can run builds _**without**_ root using the `rootless` setup [referenced in the issue](https://github.com/lineageos4microg/docker-lineage-cicd/issues/407#issuecomment-1493086454). This is how I use it for my own builds when  building locally.
> 
> We (I) don't particularly want it because:
>     1. _**any**_ change risks breaking existing functionality;
>     2. this change adds a level of complexity - not huge, but there nevertheless;
>     3. to justify the risk, the change needs to bring _**significant**_ benefit. I am still not sure what benefit this feature provides.  I'm happy to accept that at least one or two users would find it useful. I'm still not sure that this is enough of a benefit to justify the risk.

Having looked a the latest code changes, I still think that the proposed changes introduce significant complexity, without adding _**significant**_ benefit. 
- you are already using this in your own fork 
- @ShadwDrgn has not responded to say that they still want this functionality 
- the original feature request was created in April 2023, and no other user has commented (here or in XDA) to say they want the feature.

You wrote
> From what I understand right now it (docker rootless) though has drawbacks IMHO which add motivation for this PR:
>     * The rootless daemon seems to be a bit cumbersome to setup, increasing the hurdle to use this repo for setting up a  development environment.
>     * It might not be possible to have rootless and rooted docker containers running side by side at the same time, as only one of the docker daemons might run at the same time. This PR adds the possibility to decide to use a non root user if the system needs to run rooted containers aside.

I disagree with the first point: `docker rootless` was trivially easy to setup when I did it: just  run a shell script .

As for the second point, I'm not sure how many users will ever want to run two instances of this docker image in parallel, one as `root`, and one as a non-root user (they would need a ***very*** powerful machine for that to work 😄 ). The use case is certainly not a common one, so the benefit is pretty much hypothetical. (It may even be possible to do it already, but for a hypothetical use-case I'm not going to explore that any further.)

So, for all the reasons above, I'm not going to merge this PR. I believe this project and its users will get along fine without the change. If any users ***do*** need the change, they could use your image, or apply your changes in their own fork.

Thanks again for the time and effort you have put in to the change, and I hope you are not too disappointed that it won't be merged

**Pull request closed without merging**
